
name: mglxctl

on:
  push:
    tags: ['*']
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build .
      - name: Push docker image
        # push image only when a new tag is pushed
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          docker build . -t mgxinternal/mglxctl:${GITHUB_REF/refs\/tags\//}
          docker push mgxinternal/mglxctl:${GITHUB_REF/refs\/tags\//}
      